SET IDENTITY_INSERT [dbo].[Provinces] ON
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (1, 1, N'Abra')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (2, 1, N'Agusan del Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (3, 1, N'Agusan del Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (4, 1, N'Aklan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (5, 1, N'Albay')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (6, 1, N'Antique')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (7, 1, N'Apayao')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (8, 1, N'Aurora')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (9, 1, N'Basilan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (10, 1, N'Bataan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (11, 1, N'Batanes')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (12, 1, N'Batangas')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (13, 1, N'Benguet')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (14, 1, N'Biliran')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (15, 1, N'Bohol')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (16, 1, N'Bukidnon')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (17, 1, N'Bulacan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (18, 1, N'Cagayan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (19, 1, N'Camarines Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (20, 1, N'Camarines Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (21, 1, N'Camiguin')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (22, 1, N'Capiz')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (23, 1, N'Catanduanes')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (24, 1, N'Cavite')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (25, 1, N'Cebu')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (26, 1, N'Compostela Valley')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (27, 1, N'Cotabato')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (28, 1, N'Davao del Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (29, 1, N'Davao del Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (30, 1, N'Davao Occidental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (31, 1, N'Davao Oriental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (32, 1, N'Dinagat Islands')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (33, 1, N'Eastern Samar')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (34, 1, N'Guimaras')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (35, 1, N'Ifugao')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (36, 1, N'Ilocos Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (37, 1, N'Ilocos Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (38, 1, N'Iloilo')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (39, 1, N'Isabela')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (40, 1, N'Kalinga')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (41, 1, N'La Union')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (42, 1, N'Laguna')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (43, 1, N'Lanao del Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (44, 1, N'Lanao del Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (45, 1, N'Leyte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (46, 1, N'Maguindanao')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (47, 1, N'Marinduque')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (48, 1, N'Masbate')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (49, 1, N'Metro Manila')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (50, 1, N'Valenzuela')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (51, 1, N'Misamis Occidental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (52, 1, N'Misamis Oriental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (53, 1, N'Mountain Province')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (54, 1, N'Negros Occidental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (55, 1, N'Negros Oriental')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (56, 1, N'Northern Samar')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (57, 1, N'Nueva Ecija')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (58, 1, N'Nueva Vizcaya')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (59, 1, N'Occidental Mindoro')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (60, 1, N'Oriental Mindoro')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (61, 1, N'Palawan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (62, 1, N'Pampanga')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (63, 1, N'Pangasinan')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (64, 1, N'Quezon')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (65, 1, N'Quirino')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (66, 1, N'Rizal')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (67, 1, N'Romblon')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (68, 1, N'Samar')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (69, 1, N'Sarangani')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (70, 1, N'Siquijor')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (71, 1, N'Sorsogon')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (72, 1, N'South Cotabato')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (73, 1, N'Southern Leyte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (74, 1, N'Sultan Kudarat')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (75, 1, N'Sulu')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (76, 1, N'Surigao del Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (77, 1, N'Surigao del Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (78, 1, N'Tarlac')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (79, 1, N'Tawi-Tawi')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (80, 1, N'Zambales')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (81, 1, N'Zamboanga del Norte')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (82, 1, N'Zamboanga del Sur')
INSERT INTO [dbo].[Provinces] ([Id], [CountryId], [Name]) VALUES (83, 1, N'Zamboanga Sibugay')
SET IDENTITY_INSERT [dbo].[Provinces] OFF
