SET IDENTITY_INSERT [dbo].[Barangays] ON
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (1, 982, 1420, N' Kaybiga / Deparo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (2, 982, 1421, N' Bagumbong / Pag-asa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (3, 982, 1422, N' Novaliches', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (4, 982, 1423, N' Lilles Ville Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (5, 982, 1424, N' Captol Parkland Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (6, 982, 1425, N' Amparo Subdivision / Dela Costa Homes II Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (7, 982, 1426, N' Bankers Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (8, 982, 1427, N' Tala Leprosarium and Victory Heights', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (9, 982, 1428, N' Bagong Silang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (10, 982, 1400, N' Caloocan City Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (11, 982, 1401, N' Baesa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (12, 982, 1402, N' Santa Quiteria', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (13, 982, 1403, N' Grace Park East', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (14, 982, 1404, N' San Jose', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (15, 982, 1405, N' First Avenue to Seventh Avenue West', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (16, 982, 1406, N' Grace Park West', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (17, 982, 1407, N' University Hills', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (18, 982, 1408, N' Sangandaan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (19, 982, 1409, N' Kaunlaran Village (shared with Malabon City and Navotas)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (20, 982, 1410, N' Maypajo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (21, 982, 1411, N' Fish Market (shared with Navotas)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (22, 982, 1412, N' Isla de Cocomo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (23, 982, 1413, N' Kapitbayahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (24, 983, 1740, N' Las Piñas Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (25, 983, 1741, N' Remarville Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (26, 983, 1742, N' Pulang Lupa and Zapote', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (27, 983, 1743, N' Cut-cut', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (28, 983, 1744, N' Manuyo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (29, 983, 1745, N' Gatchalian Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (30, 983, 1746, N' Verdant Acres Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (31, 983, 1747, N' Moonwalk Subdivision and Talon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (32, 983, 1748, N' Manila Doctors Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (33, 983, 1749, N' Angela Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (34, 983, 1750, N' Almanza', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (35, 983, 1751, N' T.S. Cruz Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (36, 983, 1752, N' Soldiers Hills Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (37, 984, 1200, N' Makati Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (38, 984, 1201, N' Fort Bonifacio', N'https://en.wikipedia.org/wiki/Fort_Bonifacio')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (39, 984, 1202, N' Fort Bonifacio Naval Station', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (40, 984, 1203, N' San Antonio Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (41, 984, 1204, N' La Paz, Singkamas, and Tejeros', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (42, 984, 1205, N' Santa Cruz', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (43, 984, 1206, N' Kasilawan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (44, 984, 1207, N' Carmona and Olympia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (45, 984, 1231, N' Chino roces', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (46, 984, 1208, N' Valenzuela (includes Rizal, San Miguel, and Santiago Villages)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (47, 984, 1209, N' Bel-Air', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (48, 984, 1210, N' Poblacion', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (49, 984, 1211, N' Guadalupe Viejo (includes Palm Village)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (50, 984, 1212, N' Guadalupe Nuevo (includes Visayan Village)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (51, 984, 1213, N' Pinagkaisahan - Pitogo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (52, 984, 1214, N' Cembo and South Cembo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (53, 984, 1215, N' West Rembo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (54, 984, 1216, N' East Rembo and Malapad na Bato', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (55, 984, 1217, N' Comembo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (56, 984, 1218, N' Pembo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (57, 984, 1219, N' Forbes Park North', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (58, 984, 1220, N' Forbes Park South', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (59, 984, 1221, N' Dasmariñas Village North', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (60, 984, 1222, N' Dasmariñas Village South', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (61, 984, 1223, N' San Lorenzo Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (62, 984, 1224, N' Makati Commercial Center (Ayala Center)', N'https://en.wikipedia.org/wiki/Ayala_Center')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (63, 984, 1225, N' Urdaneta Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (64, 984, 1226, N' Ayala Avenue-Paseo de Roxas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (65, 984, 1227, N' Salcedo Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (66, 984, 1228, N' Greenbelt', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (67, 984, 1229, N' Legaspi Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (68, 984, 1230, N' Pio del Pilar', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (69, 984, 1231, N' Pasong Tamo and Ecology Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (70, 984, 1232, N' Magallanes Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (71, 984, 1233, N' Bangkal', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (72, 984, 1234, N' San Isidro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (73, 984, 1235, N' Palanan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (74, 985, 1470, N' Malabon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (75, 985, 1471, N' Catmon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (76, 985, 1472, N' Longos', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (77, 985, 1473, N' Tonsuya', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (78, 985, 1474, N' Acacia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (79, 985, 1475, N' Potrero', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (80, 985, 1476, N' Araneta Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (81, 985, 1477, N' Maysilo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (82, 985, 1478, N' Santolan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (83, 985, 1479, N' Muzon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (84, 985, 1480, N' Dampalit', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (85, 985, 1470, N' Tinajeros', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (86, 985, 1480, N' UFO', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (87, 985, 1481, N' NCR', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (88, 986, 1550, N' Mandaluyong Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (89, 986, 1551, N' Vergara', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (90, 986, 1552, N' Shaw Boulevard', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (91, 986, 1553, N' National Center for Mental Health', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (92, 986, 1554, N' East EDSA', N'https://en.wikipedia.org/wiki/EDSA_(road)')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (93, 986, 1555, N' Wack Wack', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (94, 986, 1556, N' Greenhills South', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (95, 986, 1550, N' Barangay Plainview', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (96, 987, 1000, N' Manila Central Post Office', N'https://en.wikipedia.org/wiki/Manila_Central_Post_Office')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (97, 987, 1001, N' Quiapo', N'https://en.wikipedia.org/wiki/Quiapo,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (98, 987, 1002, N' Intramuros', N'https://en.wikipedia.org/wiki/Intramuros')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (99, 987, 1003, N' Santa Cruz South', N'https://en.wikipedia.org/wiki/Santa_Cruz,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (100, 987, 1004, N' Malate', N'https://en.wikipedia.org/wiki/Malate,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (101, 987, 1005, N' San Miguel', N'https://en.wikipedia.org/wiki/San_Miguel,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (102, 987, 1006, N' Binondo', N'https://en.wikipedia.org/wiki/Binondo,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (103, 987, 1007, N' Paco', N'https://en.wikipedia.org/wiki/Paco,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (104, 987, 1008, N' Sampaloc East', N'https://en.wikipedia.org/wiki/Sampaloc,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (105, 987, 1009, N' Santa Ana', N'https://en.wikipedia.org/wiki/Santa_Ana,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (106, 987, 1010, N' San Nicolas', N'https://en.wikipedia.org/wiki/San_Nicolas,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (107, 987, 1011, N' Pandacan', N'https://en.wikipedia.org/wiki/Pandacan,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (108, 987, 1012, N' Tondo South', N'https://en.wikipedia.org/wiki/Tondo,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (109, 987, 1013, N' Tondo North', N'https://en.wikipedia.org/wiki/Tondo,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (110, 987, 1014, N' Santa Cruz North', N'https://en.wikipedia.org/wiki/Santa_Cruz,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (111, 987, 1015, N' Sampaloc West', N'https://en.wikipedia.org/wiki/Sampaloc,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (112, 987, 1016, N' Santa Mesa', N'https://en.wikipedia.org/wiki/Santa_Mesa,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (113, 987, 1017, N' San Andres', N'https://en.wikipedia.org/wiki/San_Andres,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (114, 987, 1018, N' Port Area South', N'https://en.wikipedia.org/wiki/Port_Area,_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (115, 988, 1800, N' Marikina Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (116, 988, 1801, N' San Roque-Calumpang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (117, 988, 1802, N' Industrial Valley', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (118, 988, 1803, N' Barangka and Tañong', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (119, 988, 1804, N' J. De La Peña (Provident Villages)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (120, 988, 1805, N' Malanday', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (121, 988, 1806, N' Northern and Western Marikina River', N'https://en.wikipedia.org/wiki/Marikina_River')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (122, 988, 1807, N' Concepcion 1', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (123, 988, 1808, N' Nangka', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (124, 988, 1809, N' Parang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (125, 988, 1810, N' Marikina Heights', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (126, 988, 1811, N' Concepcion 2 (SSS Vill.)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (127, 988, 0, N' Not used', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (128, 988, 1820, N' Bagong Nayon, Cupang, Mambagat, and Mayamot', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (129, 989, 1770, N' Muntinlupa Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (130, 989, 1771, N' Buli / Cupang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (131, 989, 1772, N' Bayanan / Putatan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (132, 989, 1773, N' Tunasan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (133, 989, 1776, N' Poblacion', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (134, 989, 1780, N' Ayala Alabang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (135, 989, 1781, N' Filinvest City', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (136, 989, 1799, N' Alabang', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (137, 989, 1770, N' Sucat', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (138, 990, 1411, N' Fish Market', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (139, 990, 1412, N' Isla de Cocomo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (140, 990, 1413, N' Kapitbahayan [East]', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (141, 990, 1409, N' Kaunlaran Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (142, 990, 1485, N' Navotas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (143, 990, 1489, N' Tangos', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (144, 990, 1490, N' Tanza', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (145, 991, 1778, N' Aeropark Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (146, 991, 1702, N' Baclaran', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (147, 991, 1711, N' Better Living Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (148, 991, 1720, N' BF Homes 1', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (149, 991, 1718, N' BF Homes 2', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (150, 991, 1710, N' Executive Heights Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (151, 991, 1719, N' Ireneville Subdivision I & III', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (152, 991, 1714, N' Ireneville Subdivision II', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (153, 991, 1700, N' Don Galo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (154, 991, 1717, N' Manila Memorial Park', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (155, 991, 1703, N' Marina Subdivision (Reclamation)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (156, 991, 1719, N' Maywood Village I', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (157, 991, 1716, N' Maywood Village II', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (158, 991, 1700, N' Mon-El Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (159, 991, 1712, N' Miramar Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (160, 991, 1708, N' Multinational Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (161, 991, 1705, N' Ninoy Aquino International Airport', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (162, 991, 1700, N' Parañaque CPO', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (163, 991, 1706, N' Pulo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (164, 991, 1715, N' San Antonio Valley 1', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (165, 991, 1707, N' San Antonio Valley 11 & 12', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (166, 991, 1704, N' Santo Niño', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (167, 991, 1709, N' South Admiral Village, Merville Park & Moonwalk', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (168, 991, 1701, N' Tambo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (169, 991, 1713, N' United Parañaque Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (170, 992, 1300, N' Pasay City Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (171, 992, 1301, N' Domestic Airport P.O.', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (172, 992, 1302, N' San Rafael', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (173, 992, 1303, N' San Roque', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (174, 992, 1304, N' Santa Clara', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (175, 992, 1305, N' San Jose', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (176, 992, 1306, N' San Isidro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (177, 992, 1307, N' Philippine International Convention Center', N'https://en.wikipedia.org/wiki/Philippine_International_Convention_Center')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (178, 992, 1308, N' Bay City', N'https://en.wikipedia.org/wiki/Bay_City,_Metro_Manila')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (179, 992, 1309, N' Villamor Airbase', N'https://en.wikipedia.org/wiki/Villamor_Airbase')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (180, 993, 1600, N' Pasig Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (181, 993, 1601, N' San Joaquin', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (182, 993, 1602, N' Pinagbuhatan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (183, 993, 1603, N' Kapitolyo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (184, 993, 1604, N' Ugong', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (185, 993, 1605, N' Ortigas Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (186, 993, 1606, N' Caniogan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (187, 993, 1607, N' Maybunga', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (188, 993, 1608, N' Santa Lucia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (189, 993, 1609, N' Rosario', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (190, 993, 1610, N' Santolan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (191, 993, 1611, N' Manggahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (192, 993, 1612, N' Green Park', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (193, 994, 1620, N' Aguhos', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (194, 994, 1621, N' Santa Ana', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (195, 994, 1622, N' San Roque', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (196, 994, 1623, N' San Pedro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (197, 994, 1620, N' Magtanggol', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (198, 995, 1105, N' Alicia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (199, 995, 1102, N' Amihan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (200, 995, 1106, N' Apolonio Samson', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (201, 995, 810, N' Araneta Center', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (202, 995, 1135, N' Araneta Center P.O. Boxes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (203, 995, 1106, N' Baesa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (204, 995, 1116, N' Bagbag', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (205, 995, 1110, N' Bagong Bayan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (206, 995, 1109, N' Bagumbuhay', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (207, 995, 1111, N' Bagong Lipunan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (208, 995, 1105, N' Bagong Pag-Asa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (209, 995, 1119, N' Bagong Silangan', N'https://en.wikipedia.org/wiki/Bagong_Silangan')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (210, 995, 1106, N' Bahay Toro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (211, 995, 1115, N' Balingasa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (212, 995, 1106, N' Balintawak', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (213, 995, 1106, N' Balumbato', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (214, 995, 1126, N' Batasan Hills', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (215, 995, 1109, N' Bayanihan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (216, 995, 1120, N' BF Homes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (217, 995, 1109, N' Blue Ridge', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (218, 995, 1101, N' Botocan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (219, 995, 1141, N' Broadway Center P.O. Boxes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (220, 995, 1105, N' Bungad', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (221, 995, 820, N' Bureau of Internal Revenue', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (222, 995, 1110, N' Camp Aguinaldo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (223, 995, 802, N' Camp Aguinaldo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (224, 995, 801, N' Camp Crame', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (225, 995, 1126, N' Capitol Hills/Park', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (226, 995, 1117, N' Capri', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (227, 995, 1100, N' Central', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (228, 995, 1102, N' Claro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (229, 995, 880, N' Commission on Audit', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (230, 995, 1121, N' Commonwealth', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (231, 995, 1111, N' Crame', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (232, 995, 1109, N' Cubao', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (233, 995, 1128, N' Culiat', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (234, 995, 1115, N' Damar', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (235, 995, 1104, N' Damayan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (236, 995, 1112, N' Damayan Lagi', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (237, 995, 1123, N' Damong Maliit', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (238, 995, 1105, N' Del Monte', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (239, 995, 1104, N' Diliman', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (240, 995, 1109, N' Dioquino Zobel', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (241, 995, 1113, N' Don Manuel', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (242, 995, 1113, N' Doña Aurora', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (243, 995, 1125, N' Doña Faustina Subdivision', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (244, 995, 1113, N' Doña Imelda', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (245, 995, 1113, N' Doña Josefa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (246, 995, 1102, N' Duyan-Duyan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (247, 995, 1102, N' E. Rodriguez', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (248, 995, 1109, N' Escopa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (249, 995, 1118, N' Fairview', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (250, 995, 1121, N' Fairview [North]', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (251, 995, 1122, N' Fairview [South]', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (252, 995, 1114, N' Gintong Silahis', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (253, 995, 1117, N' Gulod', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (254, 995, 1127, N' Holy Spirit', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (255, 995, 1112, N' Horseshoe', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (256, 995, 1111, N' Immaculate Concepcion', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (257, 995, 1124, N' Kaligayahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (258, 995, 1112, N' Kalusugan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (259, 995, 1102, N' Kamias', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (260, 995, 1103, N' Kamuning', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (261, 995, 1105, N' Katipunan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (262, 995, 1111, N' Kaunlaran', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (263, 995, 1112, N' Kristong Hari', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (264, 995, 1101, N' Krus na Ligas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (265, 995, 1114, N' La Loma', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (266, 995, 1103, N' Laging Handa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (267, 995, 1110, N' Libis', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (268, 995, 1114, N' Lourdes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (269, 995, 1108, N' Loyola Heights', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (270, 995, 1114, N' Maharlika', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (271, 995, 1101, N' Malaya', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (272, 995, 1109, N' Mangga', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (273, 995, 1115, N' Manresa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (274, 995, 1112, N' Mariana', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (275, 995, 1104, N' Mariblo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (276, 995, 1109, N' Marilag', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (277, 995, 1109, N' Masagana', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (278, 995, 1115, N' Masambong', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (279, 995, 1114, N' Matalahib', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (280, 995, 1119, N' Matandang Balara', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (281, 995, 1109, N' Milagrosa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (282, 995, 1138, N' Murphy District P.O. Boxes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (283, 995, 1125, N' Nagkaisang Nayon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (284, 995, 830, N' National Irrigation Administration', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (285, 995, 1104, N' Nayon Kaunlaran', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (286, 995, 1107, N' New Era', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (287, 995, 1147, N' Novaliches P.O. Boxes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (288, 995, 1123, N' Novaliches Proper', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (289, 995, 1103, N' Obrero', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (290, 995, 1101, N' Old Capitol Site', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (291, 995, 1114, N' Paang Bundok', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (292, 995, 1115, N' Pag-Ibig sa Nayon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (293, 995, 1103, N' Paligsahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (294, 995, 1105, N' Paltok', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (295, 995, 1108, N' Pansol', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (296, 995, 1104, N' Paraiso', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (297, 995, 1118, N' Pasong Putik', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (298, 995, 1107, N' Pasong Tamo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (299, 995, 1119, N' Payatas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (300, 995, 1104, N' Phil-Am', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (301, 995, 850, N' Philippine Heart Center', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (302, 995, 1111, N' Pinagkaisahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (303, 995, 1100, N' Piñahan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (304, 995, 1109, N' Project 4', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (305, 995, 1100, N' Project 6', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (306, 995, 1105, N' Project 7', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (307, 995, 1106, N' Project 8', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (308, 995, 860, N' Quezon City Hall', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (309, 995, 1102, N' Quirino District (Project 2 & 3)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (310, 995, 1105, N' R. Magsaysay', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (311, 995, 1103, N' Roxas District', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (312, 995, 1103, N' Sacred Heart', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (313, 995, 1114, N' Salvacion', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (314, 995, 1117, N' San Agustin', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (315, 995, 1105, N' San Antonio, Quezon City', N'https://en.wikipedia.org/wiki/San_Antonio,_Quezon_City')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (316, 995, 1116, N' San Bartolome', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (317, 995, 1113, N' San Isidro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (318, 995, 1114, N' San Isidro Labrador', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (319, 995, 1115, N' San Jose', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (320, 995, 1109, N' San Roque', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (321, 995, 1101, N' San Vicente', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (322, 995, 1116, N' Sangandaan (GSIS Village)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (323, 995, 1104, N' Santa Cruz', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (324, 995, 1117, N' Santa Lucia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (325, 995, 1117, N' Santa Monica', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (326, 995, 1114, N' Santa Teresita', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (327, 995, 1105, N' Santo Cristo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (328, 995, 1113, N' Santo Niño', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (329, 995, 1113, N' Santol', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (330, 995, 1116, N' Sauyo', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (331, 995, 1114, N' Sienna', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (332, 995, 1101, N' Sikatuna Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (333, 995, 1102, N' Silangan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (334, 995, 800, N' Social Security System', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (335, 995, 1109, N' Socorro', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (336, 995, 1103, N' South Triangle', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (337, 995, 1110, N' St. Ignatius', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (338, 995, 1111, N' St. Martin de Porres', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (339, 995, 1114, N' St. Peter', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (340, 995, 1109, N' Tagumpay', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (341, 995, 1110, N' Talampas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (342, 995, 1104, N' Talayan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (343, 995, 1116, N' Talipapa', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (344, 995, 1116, N' Tandang Sora', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (345, 995, 1113, N' Tatalon', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (346, 995, 1101, N' Teachers Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (347, 995, 1110, N' Ugong Norte', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (348, 995, 1106, N' Unang Sigaw', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (349, 995, 1101, N' University of the Philippines Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (350, 995, 840, N' V. Luna Hospital', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (351, 995, 1112, N' Valencia', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (352, 995, 1128, N' Vasra', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (353, 995, 870, N' Veterans Hospital', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (354, 995, 1105, N' Veterans Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (355, 995, 1109, N' Villa Maria Clara', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (356, 995, 1120, N' Violago Homes', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (357, 995, 1104, N' West Triangle', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (358, 995, 1110, N' White Plains', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (359, 996, 1500, N' San Juan Central Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (360, 996, 1502, N' Greenhills Post Office', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (361, 996, 1503, N' Greenhills [North]', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (362, 996, 1504, N' Eisenhower - Crame', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (363, 997, 1630, N' Bagumbayan; Pinagsama (including EP Village)', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (364, 997, 1636, N' Bay Breeze Executive Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (365, 997, 1631, N' Bicutan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (366, 997, 1632, N' Lower Bicutan - Ususan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (367, 997, 1633, N' Upper Bicutan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (368, 997, 1630, N' Western Bicutan (including Food Terminal, Inc. complex)', N'https://en.wikipedia.org/wiki/Food_Terminal,_Inc.')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (369, 997, 1638, N' Ligid', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (370, 997, 1634, N' Nichols - McKinley (Fort Bonifacio, Global City)', N'https://en.wikipedia.org/w/index.php?title=Fort_Bonifacio,_Global_City&action=edit&redlink=1')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (371, 997, 1638, N' Tuktukan', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (372, 997, 1637, N' Ibayo - Tipas', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (373, 997, 1634, N' Tilapya', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (374, 997, 1635, N' Ususan and Palar Village', N'')
INSERT INTO [dbo].[Barangays] ([Id], [CityMunicipalityId], [Zip], [Name], [WebLink]) VALUES (1179, 1548, 9999, N'San Agustin Norte', NULL)
SET IDENTITY_INSERT [dbo].[Barangays] OFF
