// <auto-generated />
namespace PII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateCivilStatusFieldType5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateCivilStatusFieldType5));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221851450_updateCivilStatusFieldType5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
